# Hadamard Example 1
### CS4243
#### Amir - 2022

In [2]:
from scipy.linalg import hadamard
import numpy as np
import cv2


In [3]:
# to show a 4x4 natural hadamard matrix and an 8x8 one
print('4x4 Natural Hadamard Matrix:\n', hadamard(4) )

print('\n8x8 Natural Hadamard Matrix:\n', hadamard(8) )


4x4 Natural Hadamard Matrix:
 [[ 1  1  1  1]
 [ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]

8x8 Natural Hadamard Matrix:
 [[ 1  1  1  1  1  1  1  1]
 [ 1 -1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1  1  1 -1 -1]
 [ 1 -1 -1  1  1 -1 -1  1]
 [ 1  1  1  1 -1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1]
 [ 1 -1 -1  1 -1  1  1 -1]]


In [4]:
# inline function to convert integer numbers to binary strings, and showing an example, 
# x is the number and n is the bit length of its binary representation

int2bin = lambda x, n: format(x, 'b').zfill(n)

print(int2bin(11, 6))

001011


In [5]:
# horder function to convert the row number of the natural
# hadamard matrix to the sequency ordered row number
#
def horder(b,nn): 
    jj = int2bin(b,nn)
    kk = ''
    for j in range(nn): 
        kk = kk+jj[nn-1-j] 
    
    kkk=np.zeros(nn) 
    kkk[0] = kk[0] 
    for j in range(1,nn):
        kkk[j] = int(kkk[j-1]) ^ int(kk[j]) 
        
    k=0
    for j in range(nn):
        k = k + int(kkk[j]) * 2**(nn-1-j)  

    return int(k)

In [6]:
# h = ordhad(n) 
# generate a n*n ordered hadamard matrix
# amir - may 2022

def ordhad(n): 
    h = hadamard(n)
    hh = hadamard(n)
    nn = np.log2(n)
    for i in range(n):
        k = horder(int(i) , int(nn)) 
        hh[k][:] = h[i][:]

    return hh

In [7]:
# to show a 4x4 sequency/frequency ordered hadamard matrix and an 8x8 one
print('4x4 Freq Ordered Hadamard Matrix:\n', ordhad(4) )

print('\n8x8 Freq Ordered Hadamard Matrix:\n', ordhad(8) )


4x4 Freq Ordered Hadamard Matrix:
 [[ 1  1  1  1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]
 [ 1 -1  1 -1]]

8x8 Freq Ordered Hadamard Matrix:
 [[ 1  1  1  1  1  1  1  1]
 [ 1  1  1  1 -1 -1 -1 -1]
 [ 1  1 -1 -1 -1 -1  1  1]
 [ 1  1 -1 -1  1  1 -1 -1]
 [ 1 -1 -1  1  1 -1 -1  1]
 [ 1 -1 -1  1 -1  1  1 -1]
 [ 1 -1  1 -1 -1  1 -1  1]
 [ 1 -1  1 -1  1 -1  1 -1]]


In [10]:
# Hadamard matrices, 64x64
ddd = (ordhad(64) + 1 ) * 200
eee = (hadamard(64)+ 1 ) * 200 

cv2.namedWindow("Seq Ord 64", cv2.WINDOW_NORMAL)
cv2.imshow('Seq Ord 64',np.uint8(ddd))
cv2.namedWindow("Natural 64", cv2.WINDOW_NORMAL)
cv2.imshow('Natural 64',np.uint8(eee))
cv2.imwrite('ordhad64.jpg',np.uint8(ddd))
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [11]:
# Hadamard matrices, 256x256
ddd = (ordhad(256) + 1 ) * 200
eee = (hadamard(256)+ 1 ) * 200 
cv2.namedWindow("Seq Ord 256", cv2.WINDOW_NORMAL)
cv2.imshow('Seq Ord 256',np.uint8(ddd))
cv2.namedWindow("Natural 256", cv2.WINDOW_NORMAL)
cv2.imshow('Natural 256',np.uint8(eee))
cv2.imwrite('ordhad256.jpg',np.uint8(ddd))
cv2.waitKey(0)

107

In [12]:
# Example: Hadamard transform of a 512x512 image
# 1- building the freq ordered Hadamard matrix, size=512x512, equal to the supposed
# image size
h = ordhad(512)


In [14]:
# reading image, conversion to graylevel, resize to 512x512
img = cv2.imread('images/cat.bmp')

In [15]:
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img = cv2.resize(img, (512, 512))

There are three main ways to perform NumPy matrix multiplication:
* dot(array a, array b) : returns the scalar or dot product of two arrays.
* matmul(array a, array b) : returns the matrix product of two arrays.
* multiply(array a, array b) : returns the element-wise matrix multiplication of two arrays.

In [16]:
# Transform: HI = h*img*h , matrix multiplication
HI = np.matmul(h, np.matmul(img, h))

In [17]:
# showing the shape and contents of the HI, i.e. Hadamard transform of the  img
HI.shape


(512, 512)

In [18]:
HI

array([[23606677,     4373,  4912413, ...,    63125,    14945,    24609],
       [ 2958037,  4230425,  3858369, ...,     9065,     9229,    11457],
       [ 1083773,   435409, -1867383, ...,   -29819,   -15279,   -11555],
       ...,
       [  -15101,    -4257,    -1053, ...,     -317,      139,       31],
       [    8239,     4003,   -13721, ...,     -365,       35,      -57],
       [     887,    14999,     6003, ...,      -33,      255,      239]])

In [19]:
# sum of the all pixels of the img, check the HI[0,0] too !!??
np.sum(img)

23606677

In tests below we are going to build some 4x4 given binary images and compute their freq
ordered Hadamard transform to hive you some hints about an image and the distribution 
of its frequency components

In [21]:
img = np.ones((4,4))
h = ordhad(4)
H = np.matmul( h, np.matmul(img,h))
print('Image=\n', img , '\n Hadamard=')
print(H)

Image=
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 Hadamard=
[[16.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [22]:
img = [[1,1,0,0],[1,1,0,0],[1,1,0,0],[1,1,0,0]]
h = ordhad(4)
H = np.matmul( h, np.matmul(img,h))
print('Image=\n', img , '\n Hadamard=')
print(H)

Image=
 [[1, 1, 0, 0], [1, 1, 0, 0], [1, 1, 0, 0], [1, 1, 0, 0]] 
 Hadamard=
[[8 8 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [23]:
img = [[1,0,1,0],[1,0,1,0],[1,0,1,0],[1,0,1,0]]
h = ordhad(4)
H = np.matmul( h, np.matmul(img,h))
print('Image=\n', img , '\n Hadamard=')
print(H)

Image=
 [[1, 0, 1, 0], [1, 0, 1, 0], [1, 0, 1, 0], [1, 0, 1, 0]] 
 Hadamard=
[[8 0 0 8]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [24]:
img = [[1,0,1,0],[0,1,0,1],[1,0,1,0],[0,1,0,1]]
h = ordhad(4)
H = np.matmul( h, np.matmul(img,h))

print('Image=\n', img , '\n Hadamard=')
print(H)

Image=
 [[1, 0, 1, 0], [0, 1, 0, 1], [1, 0, 1, 0], [0, 1, 0, 1]] 
 Hadamard=
[[8 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 8]]


In [25]:
img = [[0,0,0,0],[0,1,1,0],[0,1,1,0],[0,0,0,0]]
h = ordhad(4)
H = np.matmul( h, np.matmul(img,h))

print('Image=\n', img , '\n Hadamard=')
print(H)

Image=
 [[0, 0, 0, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0]] 
 Hadamard=
[[ 4  0 -4  0]
 [ 0  0  0  0]
 [-4  0  4  0]
 [ 0  0  0  0]]


In [26]:
# inverse hadamard
h2 = np.dot( np.matmul( h, np.matmul(H,h)) , 1/(4**2) )
print('Image=\n', img , '\n Inverse Hadamard=')
print(h2)

Image=
 [[0, 0, 0, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0]] 
 Inverse Hadamard=
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
