# Lab 02 : Training with epochs -- demo

In [1]:
import torch

### Lets make an artificial training set of 10 images (28x28 pixels)

In [2]:
train_data = torch.rand(10,28,28)

print(train_data.size())

torch.Size([10, 28, 28])


### Lets define a the random order in which we are going to visit these images:

In [3]:
shuffled_indices = torch.randperm(10)
print(shuffled_indices)

tensor([3, 8, 0, 9, 7, 5, 1, 4, 2, 6])


### Visit the training set in this random order and do minibatch of size 2

In [4]:
bs=2

for count in range(0,10,bs):
    
    batch_of_indices = shuffled_indices[count:count+bs]
    
    print(batch_of_indices)
    
    batch_of_images = train_data[ batch_of_indices  ]

tensor([3, 8])
tensor([0, 9])
tensor([7, 5])
tensor([1, 4])
tensor([2, 6])
