# Lab 01 : Convolutional layer - demo

In [2]:
import torch
import torch.nn as nn

### Make a convolutional module
* inputs:  2 channels
* output:  5 activation maps 
* filters are 3x3
* padding with one layer of zero to not shrink anything

In [3]:
mod = nn.Conv2d( 2 , 5 ,  kernel_size=3,  padding=1 )

### Make an input 2 x 6 x 6  (two channels, each one has 6 x 6 pixels )

In [4]:
bs=1

x=torch.rand(bs,2,6,6)

print(x)

print(x.size())

tensor([[[[0.9647, 0.6641, 0.1846, 0.0741, 0.2426, 0.0286],
          [0.2926, 0.2690, 0.8945, 0.7917, 0.6449, 0.4339],
          [0.4199, 0.9387, 0.3030, 0.7605, 0.5784, 0.1366],
          [0.0920, 0.2539, 0.1089, 0.0882, 0.4449, 0.9903],
          [0.0181, 0.6897, 0.2516, 0.8399, 0.7515, 0.3681],
          [0.6694, 0.0813, 0.5470, 0.1661, 0.7311, 0.2856]],

         [[0.0572, 0.5530, 0.5090, 0.3118, 0.4822, 0.0546],
          [0.6331, 0.2684, 0.6874, 0.0646, 0.2393, 0.4566],
          [0.4991, 0.1681, 0.3625, 0.3109, 0.8576, 0.1604],
          [0.5816, 0.0894, 0.6019, 0.9650, 0.5826, 0.2410],
          [0.9037, 0.5362, 0.3347, 0.6226, 0.9154, 0.0774],
          [0.7821, 0.1263, 0.7604, 0.9761, 0.5548, 0.0411]]]])
torch.Size([1, 2, 6, 6])


### Feed it to the convolutional layer: the output should have 5 channels (each one is 6x6)

In [5]:
y=mod(x)

print(y)

print(y.size())

tensor([[[[-0.1464, -0.5058, -0.4121, -0.3813, -0.1551, -0.2146],
          [-0.1091, -0.1937, -0.4113, -0.4900, -0.4752, -0.3575],
          [-0.1968, -0.2069, -0.5147, -0.5477, -0.3661, -0.1405],
          [-0.3232, -0.2430, -0.4195, -0.3464, -0.4819, -0.2669],
          [-0.2057, -0.3815, -0.4011, -0.6929, -0.5494, -0.2856],
          [ 0.2158, -0.4186,  0.0138, -0.1730,  0.0374, -0.2357]],

         [[ 0.0326,  0.3959,  0.2708,  0.3268,  0.2733,  0.2370],
          [-0.0920,  0.4574,  0.1929,  0.4797,  0.2473,  0.2792],
          [ 0.2269,  0.2934,  0.5939,  0.0310,  0.1756,  0.4366],
          [ 0.1510,  0.0887,  0.2965,  0.3478,  0.3414,  0.1654],
          [ 0.3653,  0.3119,  0.6454,  0.2852,  0.3365,  0.3320],
          [ 0.3551,  0.4914,  0.2409,  0.5954,  0.4347,  0.2755]],

         [[ 0.0403,  0.0786,  0.4327,  0.0157,  0.0642,  0.1806],
          [ 0.3882,  0.2421,  0.1530,  0.2215,  0.3505,  0.1158],
          [ 0.1697,  0.1244,  0.3598,  0.3732,  0.4586,  0.4285],
      

### Lets look at the 5 filters.
* Our filters are 2x3x3
* Each of the filter has 2 channels because the inputs have two channels

In [6]:
print(mod.weight)

print(mod.weight.size())

Parameter containing:
tensor([[[[ 0.0769,  0.0854, -0.0457],
          [-0.2278,  0.1797, -0.2205],
          [-0.1373,  0.1309, -0.1921]],

         [[-0.2324,  0.0508,  0.1103],
          [-0.0557,  0.0228, -0.0676],
          [-0.1515, -0.2187, -0.0543]]],


        [[[-0.0162, -0.1215, -0.0105],
          [ 0.2319, -0.1407,  0.0846],
          [-0.0128, -0.0090, -0.1557]],

         [[-0.1215,  0.2144, -0.0722],
          [ 0.2164,  0.1504,  0.0624],
          [-0.0099, -0.1855,  0.2224]]],


        [[[ 0.2247, -0.0227,  0.1882],
          [ 0.1728, -0.2182, -0.1315],
          [-0.1470,  0.2327,  0.1637]],

         [[ 0.2089,  0.1279, -0.0395],
          [-0.2204, -0.1502, -0.0791],
          [-0.1176,  0.2314, -0.1635]]],


        [[[-0.0567,  0.1631, -0.0448],
          [ 0.1037, -0.1097, -0.1254],
          [ 0.2014,  0.1393, -0.0822]],

         [[-0.2334,  0.0062, -0.0660],
          [-0.0554, -0.0243,  0.1007],
          [ 0.2226,  0.1079, -0.1888]]],


        [[[-0.0275